# Generated by Django 6.0.6 on 2026-07-07 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeTicket',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket', models.JSONField()),
                ('cost', models.IntegerField()),
                ('qrcode', models.BinaryField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('concert_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('artists', models.JSONField()),
                ('dt_concert', models.DateTimeField()),
                ('duration', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.managerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertTicket',
            fields=[
                ('tier_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(default='normal', max_length=50)),
                ('cost', models.IntegerField(default=50)),
                ('description', models.TextField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.concert')),
            ],
        ),
    ]
