# Generated by Django 6.0.6 on 2026-07-07 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chatroom_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('chat_type', models.CharField(max_length=1)),
                ('message', models.TextField(null=True)),
                ('file', models.BinaryField(null=True)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('reply_id', models.UUIDField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chatroom')),
            ],
        ),
    ]
